Fastly provider
projectdiscovery/cloudlist pull request #24
Opened 2021-06-22 12:24 UTC by parrasajad

2021-06-22 12:24 UTC, parrasajad commented
#23

2021-06-22 13:16 UTC, Mzack9999 requested changes

2021-06-22 13:16 UTC, Mzack9999 commented on pkg/providers/fastly/fastly.go
> +		log.Fatal(err)
I guess it should be:
```
return nil, err
```

2021-06-22 13:40 UTC, parrasajad commented on pkg/providers/fastly/fastly.go
> +		log.Fatal(err)
Thanks @Mzack9999

2021-06-22 14:18 UTC, Mzack9999 approved these changes

2021-06-24 08:29 UTC, Ice3man543 approved these changes

2021-06-24 08:30 UTC, merged