use goflags
projectdiscovery/cloudlist pull request #40
Opened 2022-02-04 06:15 UTC by parrasajad

2022-02-04 07:57 UTC, Mzack9999 requested changes
Left some comments about `filepath` and comparison

2022-02-04 07:57 UTC, Mzack9999 commented on internal/runner/options.go
> +	defaultConfigLocation         = path.Join(userHomeDir(), "/.config/cloudlist/config.yaml")
please use `filepath`

2022-02-04 07:57 UTC, Mzack9999 commented on internal/runner/options.go
> +	defaultProviderConfigLocation = path.Join(userHomeDir(), "/.config/cloudlist/provider-config.yaml")
please use `filepath`

2022-02-04 07:57 UTC, Mzack9999 commented on internal/runner/runner.go
> +		if reflect.DeepEqual(a, e) {
Shouldn't `if strings.EqualFold(a, e) {` have the same result?

2022-02-04 19:47 UTC, ehsandeep requested changes
- [ ] adding mssing cli flag for `id` filter

```
   -id string[]            ids to fetch assets from
```
- [ ] automatic migration of current config to provider config https://github.com/projectdiscovery/cloudlist/issues/39

2022-02-07 14:40 UTC, ehsandeep approved these changes

2022-02-07 14:40 UTC, merged