Support additional services for gcp provider
projectdiscovery/cloudlist pull request #528
Opened 2024-06-12 20:29 UTC by RamanaReddy0M

2024-06-12 20:35 UTC, RamanaReddy0M commented
```console
✗ ./cloudlist -p gcp                             

  _______             _____     __ 
 / ___/ /__  __ _____/ / (_)__ / /_
/ /__/ / _ \/ // / _  / / (_-</ __/
\___/_/\___/\_,_/\_,_/_/_/___/\__/ 

                projectdiscovery.io

[INF] Current cloudlist version 1.0.8 (latest)
[INF] Listing assets from gcp (dev) provider
gcf-sources-4200296701-us-central1.storage.googleapis.com
pd-cloudlist-test-bucket.storage.googleapis.com
us-central1-universal-team-426216-k5.cloudfunctions.net
[INF] Found 3 Hosts for gcp (dev)
```

2024-06-24 11:59 UTC, dogancanbakir approved these changes

2024-06-24 11:59 UTC, dogancanbakir commented on pkg/providers/gcp/bucket.go
> +func (d *cloudStorageProvider) GetResource(ctx context.Context) (*schema.Resources, error) {
How about something like this to make it more readable?

```go
func (d *cloudStorageProvider) GetResource(ctx context.Context) (*schema.Resources, error) {
	list := schema.NewResources()

	buckets, err := d.getBuckets()
	if err != nil {
		return nil, err
	}

	for _, bucket := range buckets {
		resource := &schema.Resource{
			ID:       d.id,
			Provider: providerName,
			DNSName:  fmt.Sprintf("%s.storage.googleapis.com", bucket.Name),
		}
		isPublic, err := d.isBucketPublic(bucket.Name)
		if err == nil && isPublic {
			resource.Public = true
		}
		list.Append(resource)
	}

	return list, nil
}
```

2024-06-24 11:59 UTC, dogancanbakir commented on pkg/providers/gcp/bucket.go
> +func (d *cloudStorageProvider) GetResource(ctx context.Context) (*schema.Resources, error) {
same for other instances

2024-06-26 16:36 UTC, ehsandeep requested changes
@RamanaReddy0M we can expose service name as part of json output as well, for example:

```diff
{
  "public": true,
  "provider": "gcp",
+ "service": "s3"
  "id": "staging",
  "dns_name": "screenshot-optimized-bucket.storage.googleapis.com"
}
```

2024-06-27 05:20 UTC, ehsandeep approved these changes

2024-06-27 05:21 UTC, merged