Add aws assume role support
projectdiscovery/cloudlist pull request #551
Opened 2024-08-01 22:42 UTC by RamanaReddy0M

2024-08-14 10:43 UTC, dogancanbakir commented on pkg/providers/aws/aws.go
> +	p.Token, _ = block.GetMetadata(sessionToken)
are these optional?

2024-08-14 11:24 UTC, RamanaReddy0M commented on pkg/providers/aws/aws.go
> +	p.Token, _ = block.GetMetadata(sessionToken)
yes

2024-08-14 11:42 UTC, dogancanbakir approved these changes

2024-08-16 13:58 UTC, ehsandeep reviewed
@RamanaReddy0M Can we update the docs at https://docs.projectdiscovery.io/tools/cloudlist/providers#aws-amazon-web-services as well?

2024-08-16 14:13 UTC, ehsandeep requested changes
```console
./cloudlist -pc pc.yaml 

  _______             _____     __ 
 / ___/ /__  __ _____/ / (_)__ / /_
/ /__/ / _ \/ // / _  / / (_-</ __/
\___/_/\___/\_,_/\_,_/_/_/___/\__/ 

		projectdiscovery.io

[INF] Current cloudlist version 1.0.8 (latest)
[FTL] Could not create runner: yaml: unmarshal errors:
  line 7: cannot unmarshal !!seq into string
```

config parsing error on default run, works fine with provider filter.

2024-08-17 05:01 UTC, ehsandeep approved these changes

2024-08-17 05:01 UTC, merged